repos:
-   repo: https://github.com/Pierre-Sassoulas/black-disable-checker/
    rev: 1.0.1
    hooks:
    - id: black-disable-checker
      exclude: black_disable_checker/__main__.py|tests/fixture.py
-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    - id: black
      args: [--safe, --quiet, --line-length=120]
